- hosts: piservers
  vars:
    # your extra bundles here
    zsh_user: pi
    #zsh_shared: yes
    zsh_antigen_bundles_extras: []
    # your variables here
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - zsh
